---
- name: Swapfile | Install | Check swap file already exist
  become: True
  stat:
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    get_checksum: False
    get_md5: False
  register: swap_allocated

- name: Swapfile | Install | Make directory for swapfile
  become: True
  file:
    path: "{{ swap_file_path }}"
    state: directory
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"
    mode: "{{ swap_file_permisions }}"
  when:
    - swap_allocated.stat.exists == False
    - swap_file_path != "/"

- name: Swapfile | Install | Create swapfile with custom size
  become: True
  command: "dd if=/dev/zero of={{ swap_file_path }}/{{ swap_file_name }} bs=1M count={{ swap_custom_size_mb }}"
  when:
    - swap_custom_size
    - swap_allocated.stat.exists == False

- name: Swapfile | Install | Create swapfile with distribution recommended size
  become: True
  command: "dd if=/dev/zero of={{ swap_file_path }}/{{ swap_file_name }} bs=1M count={{ swap_size_mb }}"
  when:
    - swap_custom_size == False
    - swap_install_recommended_size
    - swap_allocated.stat.exists == False

- name: Swapfile | Install | Switch file to swap type.
  become: True
  command: "mkswap {{ swap_file_path }}/{{ swap_file_name }}"
  when:
    - swap_allocated.stat.exists == False

- name: Swapfile | Install | Set swapfile permissions
  become: True
  file:
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    mode: "{{ swap_file_permisions }}"
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"
  when:
    - swap_allocated.stat.exists == False

- name: Swapfile | Install | Enable swap file on fly.
  become: True
  command: "swapon {{ swap_file_path }}/{{ swap_file_name }}"
  when:
    - swap_allocated.stat.exists == False

#- name: Swapfile | Install | Add swap entry in fstab
#  become: True
#  mount:
#    name: none
#    src: "{{ swap_file_path }}/{{ swap_file_name }}"
#    fstype: swap
#    opts: sw,
#    dump: 0
#    passno: 0
#    state: present
#  when:
#    - swap_allocated.stat.exists == False
#
# !!! Usage of mount module disabled due overwrite bug. Will be enabled again when fixed.
# !!! Bug info to ansible link: https://github.com/ansible/ansible/issues/26036

- name: Swapfile | Install | Add swap entry in fstab
  become: True
  lineinfile:
    dest: "/etc/fstab"
    line: "{{ swap_file_path }}/{{ swap_file_name }}   none    swap    sw,pri={{ swap_file_priority | default('0') }}    0   0"
    state: present
  when:
    - swap_allocated.stat.exists == False
