---
- name: Swapfile | Install distribution recommended swapfile size
  include: recommended.yml
  when:
    - swap_files_use_distribution_recommended == True
    - ansible_memory_mb.swap.total == 0

- block:

    - name: Swapfile | Check swap size allocated space adjusted.
      include: sizecheck.yml

    - name: Swapfile | Remove old swap file.
      include: remove.yml

    - name: Swapfile | Install new swap file.
      include: install.yml

  when:
    - swap_files_use_distribution_recommended == False
    - swap_files > 0

- name: Swapfile | Check swap and swapfile settings.
  include: setup.yml
  when: (swap_set_swappiness == True) or
        (swap_set_vfs_cache_pressure == True)
