---
- name: Swapfile | Remove | Check swap file already exist
  become: True
  stat:
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    get_checksum: False
    get_md5: False
  register: swap_remove_allocated

- name: Swapfile | Remove | Disable swap file on fly.
  become: True
  command: "swapoff {{ swap_file_path }}/{{ swap_file_name }}"
  when:
    - swap_remove_allocated.stat.exists == True

- name: Swapfile | Remove | Remove swapfile
  become: True
  file:
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    state: absent
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"
    mode: "{{ swap_file_permisions }}"
  when:
    - swap_remove_allocated.stat.exists == True

- name: Swapfile | Remove | Check swapfile directory is empty
  become: True
  find:
    path: "{{ swap_file_path }}"
    recurse: yes
  register: swap_file_directory_empty

- name: Swapfile | Remove | Remove swapfile directory if empty
  become: True
  file:
    path: "{{ swap_file_path }}"
    state: absent
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"
    mode: "{{ swap_file_permisions }}"
  when:
    - swap_remove_allocated.stat.exists == True
    - swap_file_path != "/"
    - swap_file_directory_empty.matched|int == 0

#- name: Swapfile | Remove | Remove swap entry from fstab
#  become: True
#  mount:
#    name: none
#    src: "{{ swap_file_path }}/{{ swap_file_name }}"
#    fstype: swap
#    opts: sw,
#    dump: 0
#    passno: 0
#    state: absent
#  when:
#    - swap_remove_allocated.stat.exists == True
#
# !!! Usage of mount module disabled due overwrite bug. Will be enabled again when fixed.
# !!! Bug info to ansible link: https://github.com/ansible/ansible/issues/26036

- name: Swapfile | Remove | Remove swap entry from fstab
  become: True
  lineinfile:
    dest: "/etc/fstab"
    line: "{{ swap_file_path }}/{{ swap_file_name }}   none    swap    sw,pri={{ swap_file_priority | default('0') }}    0   0"
    state: absent
  when:
    - swap_remove_allocated.stat.exists == True
