---
- name: Swapfile | Remove | Clean fstab file from all swap files and partitions records
  become: True
  lineinfile:
    dest: "/etc/fstab"
    regexp: '(swap|none)[ \t]+(swap)'
    state: absent
  when:
    - swap_file_clean_fstab == True
  register: fstab_cleared

- name: Swapfile | Remove | Switch off all swap files cleared from fstab
  command: "swapoff -a"
  when:
    - fstab_cleared.changed == True

- name: Swapfile | Remove | Check swap file already exist
  become: True
  stat:
    path: "{{ item.swap_file_path }}/{{ item.swap_file_name }}"
    get_checksum: False
    get_md5: False
  when:
    - item.swap_file_allocated  == False
  with_items: "{{ swap_files }}"
  register: swap_remove_allocated

- name: Swapfile | Remove | Disable swap file on fly.
  become: True
  command: "swapoff {{ item.item.swap_file_path }}/{{ item.item.swap_file_name }}"
  when:
    - item.item.swap_file_allocated == False
    - item.stat.exists == True
    - fstab_cleared.changed == False
  with_items: "{{ swap_remove_allocated.results }}"
  ignore_errors: True

- name: Swapfile | Remove | Remove swapfile
  become: True
  file:
    path: "{{ item.item.swap_file_path }}/{{ item.item.swap_file_name }}"
    state: absent
  when:
    - item.item.swap_file_allocated == False
    - item.stat.exists == True
  with_items: "{{ swap_remove_allocated.results }}"

- name: Swapfile | Remove | Check swapfile directory is empty
  become: True
  find:
    path: "{{ item.swap_file_path }}"
    recurse: yes
  when:
    - item.swap_file_allocated  == False
    - item.swap_file_path != "/"
  with_items: "{{ swap_files }}"
  register: swap_file_directory_empty

- name: Swapfile | Remove | Remove swapfile directory if empty
  become: True
  file:
    path: "{{ item.item.swap_file_path }}"
    state: absent
  when:
    - item.item.swap_file_allocated == False
    - item.item.swap_file_path != "/"
    - item.matched|int == 0
  with_items: "{{ swap_file_directory_empty.results }}"

#- name: Swapfile | Remove | Remove swap entry from fstab
#  become: True
#  mount:
#    name: none
#    src: "{{ item.item.swap_file_path }}/{{ item.item.swap_file_name }}"
#    fstype: swap
#    opts: "sw,pri={{ item.item.swap_file_priority| default('-1') }}"
#    dump: 0
#    passno: 0
#    state: absent
#  when:
#    - item.stat.exists == True
#  with_items: "{{ swap_remove_allocated.results }}"
# !!! Usage of mount module disabled due overwrite bug. Will be enabled again when fixed.
# !!! Bug info to ansible link: https://github.com/ansible/ansible/issues/26036

- name: Swapfile | Remove | Remove swap entry from fstab
  become: True
  lineinfile:
    dest: "/etc/fstab"
    regexp: '^\{{ item.item.swap_file_path }}\/{{ item.item.swap_file_name }}\b'
    state: absent
  when:
    - item.item.swap_file_allocated == False
  with_items: "{{ swap_remove_allocated.results }}"
