---
- name: Swapfile | Set swapfile permissions
  become: True
  file: 
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    mode: "{{ swap_file_permisions }}"
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"

