---
- name: Swapfile | Configure | Permanent configure vm.swappiness
  become: True
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.swappiness = {{ swap_swappiness }}"
    regexp: '^vm.swappiness[\s]?='
    state: present
  notify: Swapfile | Handlers | Reload kernel parameters
  when: swap_set_swappiness

- name: Swapfile | Configure | Permanent configure vm.vfs_cache_pressure
  become: True
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.vfs_cache_pressure = {{ swap_vfs_cache_pressure }}"
    regexp: '^vm.vfs_cache_pressure[\s]?='
    state: present
  notify: Swapfile | Handlers | Reload kernel parameters
  when: swap_set_vfs_cache_pressure

