---
- name: Swapfile | Configure | Set swapfile permissions
  become: True
  file:
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    mode: "{{ swap_file_permisions }}"
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"

- name: Swapfile | Configure | Permanent configure vm.swappiness
  become: True
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.swappiness = {{ swap_swappiness }}"
    regexp: '^vm.swappiness[\s]?='
    state: present
  notify: Swapfile | Reload kernel parameters
  when: swap_set_swappiness

- name: Swapfile | Configure | Permanent configure vm.vfs_cache_pressure
  become: True
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.vfs_cache_pressure = {{ swap_vfs_cache_pressure }}"
    regexp: '^vm.vfs_cache_pressure[\s]?='
    state: present
  notify: Swapfile | Reload kernel parameters
  when: swap_set_vfs_cache_pressure

