---
- name: Swapfile | Configure | Permanent configure vm.swappiness
  become: True
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    reload: yes
    state: present
  when: swap_set_swappiness

- name: Swapfile | Configure | Permanent configure vm.vfs_cache_pressure
  become: True
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swap_vfs_cache_pressure }}"
    reload: yes
    state: present
  when: swap_set_vfs_cache_pressure
