---
- name: Swapfile | Set swapfile permissions
  become: True
  file:
    path: "{{ swap_file_path }}/{{ swap_file_name }}"
    mode: "{{ swap_file_permisions }}"
    owner: "{{ swap_file_owner }}"
    group: "{{ swap_file_group }}"

- name: Swapfile | Permanent onfigure vm.swappiness
  become: True
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: "vm.swappiness = {{ swap_swappiness }}"
    regexp: '^vm.swappiness[\s]?='
    state: present
  notify: Swapfile | Reload kernel parameters
  when: "{{ swap_set_swappiness }}"
